# For a quick start check out our HTTP Requests collection (Tools|HTTP Client|Open HTTP Requests Collection).
#
# Following HTTP Request Live Templates are available:
# * 'gtrp' and 'gtr' create a GET request with or without query parameters;
# * 'ptr' and 'ptrp' create a POST request with a simple or parameter-like body;
# * 'mptr' and 'fptr' create a POST request to submit a form with a text or file field (multipart/form-data);

GET http://localhost:8080/api/accounts
Accept: application/json

###

POST http://localhost:8080/api/accounts
Content-Type: application/json

{
  "email" : "jiwoo627@naver.com",
  "nickname" : "simple5757",
  "username" : "김지우",
  "password" : "지우짱짱"
}

###

POST http://localhost:8080/api/accounts
Content-Type: application/json

{
  "email" : "kiworkshop@naver.com",
  "nickname" : "kiworkshop",
  "username" : "공방",
  "password" : "공방왓썹"
}

###

POST http://localhost:8080/api/accounts/login
Content-Type: application/json

{
  "email" : "jiwoo627@naver.co",
  "password" : "지우짱"
}

###