spring:
  h2:
    console:
      enabled: true
  jpa:
    database: h2
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: create
  datasource:
    url: jdbc:h2:~/community
    data: classpath:schema-h2.sql
google:
  client:
    clientId: 448574013114-pf7qpdi0n7nqqjcuj50l5vq7kras4kqf.apps.googleusercontent.com
    clientSecret: WF7O1Hs6-g0y1ed_CYTpwQdE
    accessTokenUri: https://www.googleapis.com/oauth2/v4/token
    userAuthorizationUri: https://accounts.google.com/o/oauth2/v2/auth
    clientAuthenticationScheme: form
    scope:
      - email
      - profile
  resource:
    userInfoUri: https://www.googleapis.com/oauth2/v3/userinfo


my-app:
  admin-email: admin@email.com
  admin-nickname: adad
  admin-username: admin
  admin-password: admin!!!
  user-email: user@email.com
  user-nickname: usus
  user-username: user
  user-password: user!!!
  client-id: myApp
  client-secret: pass
logging:
  level:
    org:
      springframework:
        security: DEBUG
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE